name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build Next.js App
    runs-on: ubuntu-latest

    steps:
      # ✅ 1. ดึงโค้ดจาก repo
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ 2. ติดตั้ง Node.js เวอร์ชัน 22
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # ✅ 3. ล้าง cache เก่า
      - name: Clear cache
        run: |
          rm -rf .next
          rm -rf node_modules/.cache

      # ✅ 4. ติดตั้ง dependencies
      - name: Install dependencies
        run: npm ci

      # ✅ 5. ตรวจสอบ lint (optional)
      - name: Run linting
        run: npm run lint || echo "Lint warnings ignored"

      # ✅ 6. Build Next.js (static export)
      - name: Build Next.js app
        env:
          NEXT_PUBLIC_API_URL: https://flask-todo-app-3r5b.onrender.com/api
          NODE_ENV: production
        run: |
          npm run build
          ls -la out/
          echo "Checking for CSS files..."
          find out -name "*.css" | head -5

      # ✅ 7. Upload artifact to GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
